### ISSUE TITLE
Fix for busybox wget & https

### ISSUE THREAD

**Issue by macmpi** [maxnet/berryboot#439]
It seems busybox-wget within berryboot has some configuration problem preventing use of https URLs, which the Web now heavily rely on:
`wget: can't execute 'openssl': No such file or directory`
This makes `wget` under core berryboot (for use in `berryboot-init` scripts for instance) barely usable.

According to [busybox sources](https://git.busybox.net/busybox/tree/networking/wget.c#n49), there are 2 methods to support https link with wget (FEATURE_WGET_HTTPS and/or FEATURE_WGET_OPENSSL). According to error message the latter seems used, but then openssl has not been fully installed.

Could you please fix, whatever method is preferred in berryboot context?
Thanks!

**Comment by macmpi** [comment]
@maxnet can you elaborate on how to enable `openssl` support as it seems pieces are in the build, but it does not seem properly installed.
Thanks in advance.

**Comment by maxnet** [comment]
Problem is that it requires the `openssl` command line executable and that adds size to the image.
We currently only ship the openssl library.

**Comment by macmpi** [comment]
Would the `Support HTTPS using internal TLS code` option be possible and have lower footprint?

**Comment by maxnet** [comment]
Could be, except our 2015 busybox version doesn't have that option.

Another option is enabling full wget instead of busybox wget.
That adds to size too though.

**Comment by macmpi** [comment]
Is updating busybox a big issue? (would leverage many fixes probably).
What would be the best trade-of option in your opinion then?

With servers massively moving to `https`, it is rather limiting that core berryboot can not download files from such prevalent sources...
Appreciate your consideration.

**Comment by macmpi** [comment]
What would be the best option to download through `https` in core berryboot then? (curl, etc...)
Thanks for your thoughts.

**Comment by macmpi** [comment]
Hi,
Any plan to address this, or shall I close ticket?
Thanks for feedback.

**Comment by maxnet** [comment]
Updating busybox will be dealt with once we update to a newer buildroot version. (it also tends to like newer uclibc etc.)
Not anytime soon though.

**Comment by macmpi** [comment]
Understood.
We shall not expect any workaround in the meantime (full wget / curl / etc...)?

**Comment by maxnet** [comment]
Should be fixed in 20180904 that has newer uclibc

**Comment by macmpi** [comment]
Thanks a bunch: quite a big overhaul!
Will try to test how it plays-out with my [install/update scripts](https://github.com/macmpi/berryboot-scripts) and report: pulling scripts updates directly from github should be a breeze now.

**Comment by macmpi** [comment]
while now busybox `wget` supports lots of HTTPS URLs, I'm still having some difficulties with some servers or reflector services. GNU `wget` does not have those problems.
Similar issues and example have been [reported here](https://github.com/mirror/busybox/issues/6)

Can't figure-out where the problem could be: bug, configuration, limitation of that mode only,...
One server provider mentioned busybox `wget` might have issue with SNI support... but I have no idea how to determine if that's the gating issue, or something else.
Would you have any clue by chance?

**Comment by macmpi** [comment]
Busybox TLS ciphers limitation [is being worked-out](https://bugs.busybox.net/show_bug.cgi?id=11456): I will probably submit a PR once a new Busybox release is available with the fix.
